# Generated by Django 3.1 on 2022-08-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_offer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offerof', to='store.product'),
        ),
    ]
