# Generated by Django 3.1 on 2022-08-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discounttype',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
