# Generated by Django 3.1 on 2022-08-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20220831_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_after_discount',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
