# Generated by Django 3.1 on 2022-09-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon'),
        ('carts', '0005_cartitem_total_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
