# Generated by Django 3.1 on 2022-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved')], default='Processing', max_length=200)),
                ('return_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct')),
            ],
        ),
    ]
