# Generated by Django 3.1 on 2022-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_return_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_products',
            name='comment',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return_products',
            name='reson',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
