# Generated by Django 3.1 on 2022-08-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220830_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_products',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Processing', max_length=200),
        ),
    ]
