# Generated by Django 3.1 on 2022-08-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220830_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return_products',
            old_name='status',
            new_name='returnstatus',
        ),
    ]
