# Generated by Django 3.1 on 2022-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220901_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_after_discount',
            field=models.IntegerField(default=0),
        ),
    ]
