# Generated by Django 3.1 on 2022-09-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220901_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_after_discount',
        ),
    ]
