# Generated by Django 3.1 on 2022-09-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon'),
        ('orders', '0009_auto_20220901_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
