# Generated by Django 3.1 on 2022-09-16 09:22

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220916_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='photos/banner'),
        ),
    ]
