# Generated by Django 3.1 on 2022-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='photos/banner'),
        ),
    ]
